export const LIVE_EXECUTOR_SAFE_ERROR_CODES = Object.freeze([
  'DATABASE_IDLE_CLIENT_ERROR', 'DATABASE_FAILURE', 'DATABASE_ROLE_INVALID',
  'DATABASE_READ_FAILED', 'MIGRATION_CATALOG_INVALID', 'DATABASE_AUTHORITY_INVALID',
  'GENERATION_BINDING_INVALID', 'OPEN_WORK_BINDING_INVALID',
  'LIVE_EXECUTOR_NO_WORK', 'LIVE_EXECUTOR_FOREIGN_LEASE_ACTIVE',
  'LIVE_EXECUTOR_PASS_FAILED', 'LIVE_EXECUTOR_START_FAILED', 'OPERATION_ABORTED',
  'INVALID_LIVE_EXECUTOR_CONFIG', 'STARTUP_VALIDATION_CONSUMED',
  'CLAIM_FAILED', 'READ_MODEL_FAILED', 'PROVIDER_MISMATCH', 'GATEWAY_FAILED',
  'LEASE_LOST', 'INTENT_LEASE_LOST', 'INTENT_FENCE_LOST', 'INVALID_EVIDENCE',
  'INTENT_DUPLICATE', 'ATTEMPT_EXHAUSTED', 'ATTEMPT_CONFLICT',
  'COMMIT_FAILED', 'COMMIT_OUTCOME_UNKNOWN', 'RELEASE_FAILED', 'INVALID_INPUT',
  'INVALID_DATA', 'CONFLICT', 'ARTIFACT_CONFLICT', 'RPC_RATE_LIMITED', 'RPC_TIMEOUT',
  'RPC_UNAVAILABLE', 'RPC_RESPONSE_TOO_LARGE', 'RPC_RESPONSE_INVALID',
  'GENESIS_MISMATCH', 'CALL_BUDGET_EXCEEDED', 'RPC_CALL_BUDGET_EXHAUSTED', 'SESSION_FAILED',
  'SIGNED_TRANSACTION_INVALID', 'SIGNED_SIMULATION_FAILED', 'SIGNED_SIMULATION_INCONSISTENT',
  'SIGNED_SIMULATION_CONTEXT_INVALID', 'PERSISTED_TRANSACTION_INVALID',
  'SUBMISSION_AMBIGUOUS', 'SUBMISSION_SIGNATURE_MISMATCH', 'PREFLIGHT_EXPIRED',
  'CONTROL_STOPPED', 'LIVE_TRANSACTION_PREPARATION_FAILED', 'KEYPAIR_UNAVAILABLE',
  'KEYPAIR_PERMISSIONS_INVALID', 'QUOTE_MINT_NOT_ALLOWED', 'VENUE_UNAVAILABLE',
  'EXECUTION_EVIDENCE_INVALID', 'SELL_QUOTE_UNAVAILABLE', 'UNSUPPORTED_TOKEN_EXTENSION',
  'STALE_MEASUREMENT', 'OPERATION_UNAVAILABLE',
] as const);

export type LiveExecutorSafeErrorCode = typeof LIVE_EXECUTOR_SAFE_ERROR_CODES[number];
export const LIVE_EXECUTOR_SAFE_ERROR_CODE_SET: ReadonlySet<string> = new Set(
  LIVE_EXECUTOR_SAFE_ERROR_CODES,
);
