import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
import { z } from 'zod';

export const OFFICIAL_PUMP_AMM_IDL_REVISION =
  '9c82f61cb711b044a17f770ab8ce9f9bdf78f333';
export const OFFICIAL_PUMP_AMM_IDL_SHA256 =
  '6b5c7ec4e5ef9742fa99dc57b0d75b1031b379bba02a7e1b3c5a4cad68d77e56';

const PUMPSWAP_PROGRAM_ID = 'pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA';
const REQUIRED_INSTRUCTIONS = [
  'buy',
  'buy_exact_quote_in',
  'create_pool',
  'sell',
] as const;
const REQUIRED_EVENTS = ['BuyEvent', 'CreatePoolEvent', 'SellEvent'] as const;
const REQUIRED_ACCOUNTS = ['FeeConfig', 'GlobalConfig', 'Pool'] as const;
const REQUIRED_TYPES = [
  'BuyEvent',
  'CreatePoolEvent',
  'FeeConfig',
  'FeeTier',
  'Fees',
  'OptionBool',
  'Pool',
  'SellEvent',
] as const;

const discriminatorSchema = z
  .array(z.number().int().min(0).max(255))
  .length(8);
const namedSchema = z.object({ name: z.string() }).loose();
const idlSchema = z.object({
  address: z.string(),
  instructions: z.array(z.object({
    name: z.string(),
    discriminator: discriminatorSchema,
    accounts: z.array(namedSchema),
    args: z.array(z.object({ name: z.string(), type: z.unknown() })),
  }).loose()),
  events: z.array(z.object({
    name: z.string(),
    discriminator: discriminatorSchema,
  }).loose()),
  accounts: z.array(z.object({
    name: z.string(),
    discriminator: discriminatorSchema,
  }).loose()),
  types: z.array(z.object({ name: z.string(), type: z.unknown() }).loose()),
});

function selectUnique<T extends { readonly name: string }>(
  values: readonly T[],
  names: readonly string[],
  label: string,
): Record<string, T> {
  return Object.fromEntries(names.map((name) => {
    const matches = values.filter((value) => value.name === name);
    const match = matches[0];
    if (matches.length !== 1 || match === undefined) {
      throw new Error(`${label} ${name}: ${matches.length} occurrence(s).`);
    }
    return [name, match];
  }));
}

export function renderPumpSwapIdlModule(json: string): string {
  const checksum = createHash('sha256').update(json).digest('hex');
  if (checksum !== OFFICIAL_PUMP_AMM_IDL_SHA256) {
    throw new Error(`Checksum IDL PumpSwap inattendu: ${checksum}.`);
  }
  const idl = idlSchema.parse(JSON.parse(json) as unknown);
  if (idl.address !== PUMPSWAP_PROGRAM_ID) {
    throw new Error(`Programme PumpSwap inattendu: ${idl.address}.`);
  }
  const instructions = selectUnique(
    idl.instructions,
    REQUIRED_INSTRUCTIONS,
    'Instruction',
  );
  const events = selectUnique(idl.events, REQUIRED_EVENTS, 'Événement');
  const accounts = selectUnique(idl.accounts, REQUIRED_ACCOUNTS, 'Compte');
  const types = selectUnique(idl.types, REQUIRED_TYPES, 'Type');
  return [
    '// Generated by scripts/generate-pumpswap-idl.ts. Do not edit.',
    `export const PUMPSWAP_IDL_REVISION = '${OFFICIAL_PUMP_AMM_IDL_REVISION}';`,
    `export const PUMPSWAP_IDL_SHA256 = '${OFFICIAL_PUMP_AMM_IDL_SHA256}';`,
    `export const PUMPSWAP_INSTRUCTIONS = ${JSON.stringify(instructions, null, 2)} as const;`,
    `export const PUMPSWAP_EVENTS = ${JSON.stringify(events, null, 2)} as const;`,
    `export const PUMPSWAP_ACCOUNTS = ${JSON.stringify(accounts, null, 2)} as const;`,
    `export const PUMPSWAP_TYPES = ${JSON.stringify(types, null, 2)} as const;`,
    '',
  ].join('\n');
}

async function main(): Promise<void> {
  const snapshot = new URL(
    '../vendor/pumpfun/idl/pump-amm-9c82f61.json',
    import.meta.url,
  );
  const outputDirectory = new URL(
    '../src/markets/pumpswap/generated/',
    import.meta.url,
  );
  const output = new URL('pumpswap-idl.ts', outputDirectory);
  const rendered = renderPumpSwapIdlModule(await readFile(snapshot, 'utf8'));
  if (process.argv.includes('--check')) {
    if (await readFile(output, 'utf8') !== rendered) {
      throw new Error('Le module PumpSwap IDL généré est obsolète.');
    }
    return;
  }
  await mkdir(outputDirectory, { recursive: true });
  await writeFile(output, rendered);
}

if (
  process.argv[1] !== undefined
  && import.meta.url === pathToFileURL(process.argv[1]).href
) {
  await main();
}
