import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
import { z } from 'zod';

export const OFFICIAL_PUMP_IDL_REVISION =
  '9c82f61cb711b044a17f770ab8ce9f9bdf78f333';
export const OFFICIAL_PUMP_IDL_SHA256 =
  'b90bc471327f671449271d5d1d42354d1fae6f5a06502f5834459a3108138e49';

const PUMP_PROGRAM_ID = '6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P';
const REQUIRED_INSTRUCTIONS = [
  'buy',
  'buy_exact_quote_in_v2',
  'buy_exact_sol_in',
  'buy_v2',
  'create',
  'create_v2',
  'sell',
  'sell_v2',
] as const;
const REQUIRED_EVENTS = ['CreateEvent', 'TradeEvent'] as const;
const REQUIRED_TYPES = [
  'CreateEvent',
  'OptionBool',
  'Shareholder',
  'TradeEvent',
] as const;

const discriminatorSchema = z
  .array(z.number().int().min(0).max(255))
  .length(8);
const idlSchema = z.object({
  address: z.string(),
  instructions: z.array(z.object({
    name: z.string(),
    discriminator: discriminatorSchema,
    accounts: z.array(z.object({ name: z.string() }).loose()),
    args: z.array(z.object({ name: z.string(), type: z.unknown() })),
  })),
  events: z.array(z.object({
    name: z.string(),
    discriminator: discriminatorSchema,
  })),
  types: z.array(z.object({ name: z.string(), type: z.unknown() })),
});

function selectUnique<T extends { readonly name: string }>(
  values: readonly T[],
  names: readonly string[],
  label: string,
): Record<string, T> {
  return Object.fromEntries(names.map((name) => {
    const matches = values.filter((value) => value.name === name);
    const match = matches[0];
    if (matches.length !== 1 || match === undefined) {
      throw new Error(`${label} ${name}: ${matches.length} occurrence(s).`);
    }
    return [name, match];
  }));
}

export function renderPumpIdlModule(json: string): string {
  const checksum = createHash('sha256').update(json).digest('hex');
  if (checksum !== OFFICIAL_PUMP_IDL_SHA256) {
    throw new Error(`Checksum IDL Pump inattendu: ${checksum}.`);
  }

  const idl = idlSchema.parse(JSON.parse(json) as unknown);
  if (idl.address !== PUMP_PROGRAM_ID) {
    throw new Error(`Programme Pump inattendu: ${idl.address}.`);
  }

  const instructions = selectUnique(
    idl.instructions,
    REQUIRED_INSTRUCTIONS,
    'Instruction',
  );
  const events = selectUnique(idl.events, REQUIRED_EVENTS, 'Événement');
  const types = selectUnique(idl.types, REQUIRED_TYPES, 'Type');

  return [
    '// Generated by scripts/generate-pumpfun-idl.ts. Do not edit.',
    `export const PUMP_IDL_REVISION = '${OFFICIAL_PUMP_IDL_REVISION}';`,
    `export const PUMP_IDL_SHA256 = '${OFFICIAL_PUMP_IDL_SHA256}';`,
    `export const PUMP_INSTRUCTIONS = ${JSON.stringify(instructions, null, 2)} as const;`,
    `export const PUMP_EVENTS = ${JSON.stringify(events, null, 2)} as const;`,
    `export const PUMP_TYPES = ${JSON.stringify(types, null, 2)} as const;`,
    '',
  ].join('\n');
}

async function main(): Promise<void> {
  const snapshot = new URL(
    '../vendor/pumpfun/idl/pump-9c82f61.json',
    import.meta.url,
  );
  const outputDirectory = new URL(
    '../src/launchpads/pumpfun/generated/',
    import.meta.url,
  );
  const output = new URL('pump-idl.ts', outputDirectory);
  const rendered = renderPumpIdlModule(await readFile(snapshot, 'utf8'));

  if (process.argv.includes('--check')) {
    if (await readFile(output, 'utf8') !== rendered) {
      throw new Error('Le module Pump IDL généré est obsolète.');
    }
    return;
  }

  await mkdir(outputDirectory, { recursive: true });
  await writeFile(output, rendered);
}

if (
  process.argv[1] !== undefined
  && import.meta.url === pathToFileURL(process.argv[1]).href
) {
  await main();
}
